package gui;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import database.DBConnection;
import gui.ExcelExporter;
import gui.PDFExporter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vedhant Sawant
 */
public class DeptSupervisionForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeptSupervisionForm.class.getName());

    /**
     * Creates new form DeptSupervisionForm
     */
    public DeptSupervisionForm() {
        initComponents();
        cmbDepartment.removeAllItems(); 
    loadDepartments(); 
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbDepartment = new javax.swing.JComboBox<>();
        btnLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDept = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLoad.setText("Load");
        btnLoad.addActionListener(this::btnLoadActionPerformed);

        tblDept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDept);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnExport.setText("Export Excel");
        btnExport.addActionListener(this::btnExportActionPerformed);

        btnPDF.setText("Export PDF");
        btnPDF.addActionListener(this::btnPDFActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLoad))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnExport)
                                .addGap(3, 3, 3)
                                .addComponent(btnPDF))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btnBack)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport)
                    .addComponent(btnPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void loadDepartments() {
    try {
        Connection con = DBConnection.getConnection();

        String sql = "SELECT DISTINCT department FROM teacher";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            cmbDepartment.addItem(rs.getString("department"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
}
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
         try {
        Connection con = DBConnection.getConnection();

        String dept = cmbDepartment.getSelectedItem().toString();

        // 🔹 Get exam dates
        String examSql = "SELECT DISTINCT exam_date FROM exam ORDER BY exam_date";
        PreparedStatement pstExam = con.prepareStatement(examSql);
        ResultSet rsExam = pstExam.executeQuery();

        java.util.ArrayList<String> dates = new java.util.ArrayList<>();

        while (rsExam.next()) {
            dates.add(rsExam.getString("exam_date"));
        }

        // 🔹 Columns
        java.util.Vector<String> columns = new java.util.Vector<>();
        columns.add("Teacher Name");

        for (String d : dates) {
            columns.add(d);
        }

        // 🔹 Data
        java.util.Vector<java.util.Vector<Object>> data = new java.util.Vector<>();

        String teacherSql = "SELECT * FROM teacher WHERE department=?";
        PreparedStatement pstTeacher = con.prepareStatement(teacherSql);
        pstTeacher.setString(1, dept);

        ResultSet rsTeacher = pstTeacher.executeQuery();

        while (rsTeacher.next()) {

            int teacherId = rsTeacher.getInt("teacher_id");
            String teacherName = rsTeacher.getString("teacher_name");

            java.util.Vector<Object> row = new java.util.Vector<>();
            row.add(teacherName);

            for (String d : dates) {

                String checkSql =
                    "SELECT e.session FROM supervision s " +
                    "JOIN exam e ON s.exam_id = e.exam_id " +
                    "WHERE s.teacher_id=? AND e.exam_date=?";

                PreparedStatement pstCheck = con.prepareStatement(checkSql);
                pstCheck.setInt(1, teacherId);
                pstCheck.setString(2, d);

                ResultSet rsCheck = pstCheck.executeQuery();

                if (rsCheck.next()) {
                    String session = rsCheck.getString("session");
                    row.add("✔ " + session.charAt(0)); // M / E
                } else {
                    row.add("-");
                }
            }

            data.add(row);
        }

        DefaultTableModel model = new DefaultTableModel(data, columns);
        tblDept.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new MainDashboard().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        ExcelExporter.exportTable(tblDept);
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
    PDFExporter.exportTable(tblDept);        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeptSupervisionForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPDF;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDept;
    // End of variables declaration//GEN-END:variables
}
