/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import database.DBConnection;

/**
 *
 * @author Vedhant Sawant
 */
public class GenerateChartForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerateChartForm.class.getName());

    /**
     * Creates new form GenerateChartForm
     */
    public GenerateChartForm() {
        initComponents();
        loadTeachers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvailability = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Generate Chart");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        tblAvailability.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAvailability);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(338, 338, 338))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MainDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

    Connection con = DBConnection.getConnection();

    // 🔴 Clear old supervision data
    PreparedStatement clear =
            con.prepareStatement("DELETE FROM supervision");

    clear.executeUpdate();

    // ✅ GET EXAMS
    String examQuery = "SELECT * FROM exam";

    PreparedStatement pst2 =
            con.prepareStatement(examQuery);

    ResultSet rsExams = pst2.executeQuery();

    // 🔥 Teacher class
    class Teacher {

        int id;
        String name;

        Teacher(int id, String name) {
            this.id = id;
            this.name = name;
        }
    }

    java.util.ArrayList<Teacher> teachers =
            new java.util.ArrayList<>();

    // ✅ Get available teachers
    for (int i = 0; i < tblAvailability.getRowCount(); i++) {

        boolean notAvailable =
                (boolean) tblAvailability.getValueAt(i, 2);

        if (!notAvailable) {

            int id = Integer.parseInt(
                    tblAvailability.getValueAt(i, 0).toString());

            String name =
                    tblAvailability.getValueAt(i, 1).toString();

            teachers.add(new Teacher(id, name));
        }
    }

    // ❌ No teachers
    if (teachers.size() == 0) {

        JOptionPane.showMessageDialog(
                this,
                "No available teachers selected!"
        );

        return;
    }

    int roomNo = 101;

    // ✅ ASSIGN TEACHERS RANDOMLY
    while (rsExams.next()) {

        int examId = rsExams.getInt("exam_id");

        String date = rsExams.getString("exam_date");

        // 🔀 Randomize teacher order every exam
        java.util.Collections.shuffle(teachers);

        boolean assigned = false;

        for (Teacher t : teachers) {

            // 🔍 Check if teacher already assigned on same date
            String checkSql =
                    "SELECT * FROM supervision s " +
                    "JOIN exam e ON s.exam_id = e.exam_id " +
                    "WHERE s.teacher_id=? AND e.exam_date=?";

            PreparedStatement pstCheck =
                    con.prepareStatement(checkSql);

            pstCheck.setInt(1, t.id);
            pstCheck.setString(2, date);

            ResultSet rsCheck = pstCheck.executeQuery();

            // ✅ Teacher free
            if (!rsCheck.next()) {

                String insert =
                        "INSERT INTO supervision " +
                        "(teacher_id, exam_id, room_no) " +
                        "VALUES (?, ?, ?)";

                PreparedStatement pst3 =
                        con.prepareStatement(insert);

                pst3.setInt(1, t.id);
                pst3.setInt(2, examId);
                pst3.setInt(3, roomNo++);

                pst3.executeUpdate();

                assigned = true;

                break;
            }
        }

        // ❌ No teacher available
        if (!assigned) {

            JOptionPane.showMessageDialog(
                    this,
                    "Not enough teachers for date: " + date
            );

            return;
        }
    }

    JOptionPane.showMessageDialog(
            this,
            "Chart Generated Successfully"
    );

    // 🔥 OPEN VIEW FORM
    new ViewSupervisionForm().setVisible(true);

    this.dispose();

} catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed
private void loadTeachers() {
try {
        Connection con = DBConnection.getConnection();

        String sql = "SELECT teacher_id, teacher_name FROM teacher";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model =
            new DefaultTableModel(
                new Object[]{"Teacher ID", "Teacher Name", "Not Available"}, 0
            ) {
                @Override
                public Class<?> getColumnClass(int column) {
                    if (column == 2) return Boolean.class;
                    return String.class;
                }
            };

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("teacher_id"),
                rs.getString("teacher_name"),
                false
            });
        }

        tblAvailability.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GenerateChartForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAvailability;
    // End of variables declaration//GEN-END:variables
}
